-- Pokemon Seed Data for Cloudflare D1

INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('ca3cab1d-5f41-4a28-84b9-ce01c4d90480', 'Sparklefluff', 'Electric', 'A fluffy cloud creature that shoots rainbow lightning! ⚡✨', 'https://api.dicebear.com/7.x/bottts/svg?seed=sparklefluff&backgroundColor=yellow', 'Rare', 75);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('dad41811-cc22-43c4-a979-ac91d7ae6053', 'Bubbleblob', 'Water', 'A jiggly water balloon friend that loves to splash! 💧🎈', 'https://api.dicebear.com/7.x/bottts/svg?seed=bubbleblob&backgroundColor=blue', 'Common', 45);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('da5d6d91-33c6-486d-99c4-0e1538b44fde', 'Gigglewing', 'Fairy', 'Giggles so much it floats in the air! Makes everyone laugh! 😄✨', 'https://api.dicebear.com/7.x/bottts/svg?seed=gigglewing&backgroundColor=pink', 'Uncommon', 55);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('614fae4a-c042-41c7-b1ba-24f4b40e7b28', 'Blazetail', 'Fire', 'A speedy fox with a flaming tail! Super fast and warm! 🔥🦊', 'https://api.dicebear.com/7.x/bottts/svg?seed=blazetail&backgroundColor=red', 'Rare', 80);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('0671d0e7-26c3-440a-bc1d-2f0d05b016f1', 'Leafhopper', 'Grass', 'Hops around gardens and makes flowers bloom instantly! 🌿🌸', 'https://api.dicebear.com/7.x/bottts/svg?seed=leafhopper&backgroundColor=green', 'Common', 50);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('55d41032-feed-4458-8be4-9cdf5acd3f06', 'Crystalwing', 'Dragon', 'A majestic dragon with crystalline wings that shimmer in moonlight! 🐉💎', 'https://api.dicebear.com/7.x/bottts/svg?seed=crystalwing&backgroundColor=purple', 'Legendary', 95);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('6096024b-f559-47c4-8b12-ae6797a61fb8', 'Frostbite', 'Ice', 'A tiny snow sprite that turns everything into winter wonderland! ❄️✨', 'https://api.dicebear.com/7.x/bottts/svg?seed=frostbite&backgroundColor=cyan', 'Uncommon', 60);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('8bfb5b9e-146f-451f-8263-40b3e63a621b', 'Thunderclaw', 'Electric', 'Lightning fast with electric claws! Watch out! ⚡👾', 'https://api.dicebear.com/7.x/bottts/svg?seed=thunderclaw&backgroundColor=yellow', 'Epic', 85);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('44517e1c-d455-4804-aa27-ccfb9f0796e0', 'Pebblestack', 'Rock', 'A stack of friendly rocks that loves rolling downhill! 🪨😊', 'https://api.dicebear.com/7.x/bottts/svg?seed=pebblestack&backgroundColor=grey', 'Common', 40);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('57afd756-b196-44a6-97e9-be0318ca1cf6', 'Skydancer', 'Flying', 'Dances through the clouds with grace and joy! ☁️🕊️', 'https://api.dicebear.com/7.x/bottts/svg?seed=skydancer&backgroundColor=lightblue', 'Rare', 70);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('fd220d4a-b461-44b7-8e63-aa5544768927', 'Mindwhisper', 'Psychic', 'Reads thoughts and sends good vibes to everyone! 🔮✨', 'https://api.dicebear.com/7.x/bottts/svg?seed=mindwhisper&backgroundColor=violet', 'Epic', 88);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('e552c900-a2a5-45c8-a37b-4fc24fd519c5', 'Dreamweaver', 'Fairy', 'Weaves beautiful dreams and makes wishes come true! 🌙✨', 'https://api.dicebear.com/7.x/bottts/svg?seed=dreamweaver&backgroundColor=lavender', 'Legendary', 92);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('3688e754-d507-4a1e-b2e4-250aac622aa7', 'Volcanoar', 'Fire', 'Lives in volcanoes and loves spicy food! 🌋🔥', 'https://api.dicebear.com/7.x/bottts/svg?seed=volcanoar&backgroundColor=orange', 'Epic', 86);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('d4e25885-da33-42f5-9138-0a36a863b533', 'Tidalwave', 'Water', 'Rides the biggest waves and loves surfing! 🌊🏄', 'https://api.dicebear.com/7.x/bottts/svg?seed=tidalwave&backgroundColor=teal', 'Rare', 78);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('33337f4e-263f-4512-a489-244c5c85fd3c', 'Vinewhip', 'Grass', 'Swings from vines and protects the forest! 🌿🌳', 'https://api.dicebear.com/7.x/bottts/svg?seed=vinewhip&backgroundColor=olive', 'Uncommon', 58);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('e339e7c5-d2a1-40ee-81da-7f93e9011efa', 'Stargazer', 'Dragon', 'A celestial dragon that controls the stars! ⭐🐲', 'https://api.dicebear.com/7.x/bottts/svg?seed=stargazer&backgroundColor=indigo', 'Legendary', 98);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('3602a562-f4d5-479e-a4ff-ef7d596b976a', 'Glacierpaw', 'Ice', 'Leaves frost trails wherever it walks! ❄️🐾', 'https://api.dicebear.com/7.x/bottts/svg?seed=glacierpaw&backgroundColor=lightcyan', 'Rare', 72);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('265b536b-910f-479b-82f2-b1aecb799d31', 'Zappyhopper', 'Electric', 'Hops around charging batteries and making lights flicker! ⚡🦘', 'https://api.dicebear.com/7.x/bottts/svg?seed=zappyhopper&backgroundColor=gold', 'Common', 48);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('ca934b45-0a34-4c67-94f8-291db3d09c0c', 'Boulderbash', 'Rock', 'Tough as rocks and always ready to help! 🪨💪', 'https://api.dicebear.com/7.x/bottts/svg?seed=boulderbash&backgroundColor=brown', 'Uncommon', 62);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('023afaf0-bbc7-4e98-991d-5b4289f33536', 'Cloudsoar', 'Flying', 'Soars above the clouds and loves heights! ☁️🦅', 'https://api.dicebear.com/7.x/bottts/svg?seed=cloudsoar&backgroundColor=skyblue', 'Uncommon', 56);

-- Total Pokemon: 20
