-- Pokemon Seed Data for Cloudflare D1

INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('6739f5b9-7771-4841-9b41-4e275086bb27', 'Sparklefluff', 'Electric', 'A fluffy cloud creature that shoots rainbow lightning! ⚡✨', 'https://api.dicebear.com/7.x/bottts/svg?seed=sparklefluff&backgroundColor=yellow', 'Rare', 75);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('ee010218-6b1e-478a-8e85-7ded1ab60c0c', 'Bubbleblob', 'Water', 'A jiggly water balloon friend that loves to splash! 💧🎈', 'https://api.dicebear.com/7.x/bottts/svg?seed=bubbleblob&backgroundColor=blue', 'Common', 45);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('873948f0-e737-44d4-9137-a181b880b5db', 'Gigglewing', 'Fairy', 'Giggles so much it floats in the air! Makes everyone laugh! 😄✨', 'https://api.dicebear.com/7.x/bottts/svg?seed=gigglewing&backgroundColor=pink', 'Uncommon', 55);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('acace4b9-5aff-491b-8f78-a41a089e31c2', 'Blazetail', 'Fire', 'A speedy fox with a flaming tail! Super fast and warm! 🔥🦊', 'https://api.dicebear.com/7.x/bottts/svg?seed=blazetail&backgroundColor=red', 'Rare', 80);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('d350bb9b-ec95-4a68-974c-eccf77ddaedd', 'Leafhopper', 'Grass', 'Hops around gardens and makes flowers bloom instantly! 🌿🌸', 'https://api.dicebear.com/7.x/bottts/svg?seed=leafhopper&backgroundColor=green', 'Common', 50);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('08f09f05-8776-4a0f-8d5a-fadc8f24ea69', 'Crystalwing', 'Dragon', 'A majestic dragon with crystalline wings that shimmer in moonlight! 🐉💎', 'https://api.dicebear.com/7.x/bottts/svg?seed=crystalwing&backgroundColor=purple', 'Legendary', 95);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('ddbdd05e-4e2d-4c26-a59b-374325e78797', 'Frostbite', 'Ice', 'A tiny snow sprite that turns everything into winter wonderland! ❄️✨', 'https://api.dicebear.com/7.x/bottts/svg?seed=frostbite&backgroundColor=cyan', 'Uncommon', 60);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('47e46a14-0604-42b4-8a69-4abe94dfac55', 'Thunderclaw', 'Electric', 'Lightning fast with electric claws! Watch out! ⚡👾', 'https://api.dicebear.com/7.x/bottts/svg?seed=thunderclaw&backgroundColor=yellow', 'Epic', 85);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('6e095ff1-b6ff-474d-8124-0dca46f18518', 'Pebblestack', 'Rock', 'A stack of friendly rocks that loves rolling downhill! 🪨😊', 'https://api.dicebear.com/7.x/bottts/svg?seed=pebblestack&backgroundColor=grey', 'Common', 40);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('d35d6bb1-e668-4ae0-92bd-c11d0196514c', 'Skydancer', 'Flying', 'Dances through the clouds with grace and joy! ☁️🕊️', 'https://api.dicebear.com/7.x/bottts/svg?seed=skydancer&backgroundColor=lightblue', 'Rare', 70);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('6757814e-f030-4120-8b32-c23c5c2eab26', 'Mindwhisper', 'Psychic', 'Reads thoughts and sends good vibes to everyone! 🔮✨', 'https://api.dicebear.com/7.x/bottts/svg?seed=mindwhisper&backgroundColor=violet', 'Epic', 88);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('91e1e516-59d2-418a-a5c5-f1f996df7c9f', 'Dreamweaver', 'Fairy', 'Weaves beautiful dreams and makes wishes come true! 🌙✨', 'https://api.dicebear.com/7.x/bottts/svg?seed=dreamweaver&backgroundColor=lavender', 'Legendary', 92);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('70b2fdc0-a5de-4c84-bf85-974e67722125', 'Volcanoar', 'Fire', 'Lives in volcanoes and loves spicy food! 🌋🔥', 'https://api.dicebear.com/7.x/bottts/svg?seed=volcanoar&backgroundColor=orange', 'Epic', 86);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('718672cf-2517-4218-badb-f02837c660e5', 'Tidalwave', 'Water', 'Rides the biggest waves and loves surfing! 🌊🏄', 'https://api.dicebear.com/7.x/bottts/svg?seed=tidalwave&backgroundColor=teal', 'Rare', 78);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('78f6ac78-50d4-468f-9c7e-475a33a76ead', 'Vinewhip', 'Grass', 'Swings from vines and protects the forest! 🌿🌳', 'https://api.dicebear.com/7.x/bottts/svg?seed=vinewhip&backgroundColor=olive', 'Uncommon', 58);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('58c5c37d-05c6-4515-a61c-72bee1c5fc81', 'Stargazer', 'Dragon', 'A celestial dragon that controls the stars! ⭐🐲', 'https://api.dicebear.com/7.x/bottts/svg?seed=stargazer&backgroundColor=indigo', 'Legendary', 98);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('fb74284f-185f-4b40-ab06-f3e9c46c627a', 'Glacierpaw', 'Ice', 'Leaves frost trails wherever it walks! ❄️🐾', 'https://api.dicebear.com/7.x/bottts/svg?seed=glacierpaw&backgroundColor=lightcyan', 'Rare', 72);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('8bcf4e0b-ab62-4ddd-8b7a-a23af4ea5466', 'Zappyhopper', 'Electric', 'Hops around charging batteries and making lights flicker! ⚡🦘', 'https://api.dicebear.com/7.x/bottts/svg?seed=zappyhopper&backgroundColor=gold', 'Common', 48);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('36c81f44-c53f-4c68-9648-d49940393bee', 'Boulderbash', 'Rock', 'Tough as rocks and always ready to help! 🪨💪', 'https://api.dicebear.com/7.x/bottts/svg?seed=boulderbash&backgroundColor=brown', 'Uncommon', 62);
INSERT INTO pokemon (id, name, type, description, image_url, rarity, power_level) VALUES ('1e3fd9f6-23b3-4066-b57e-0f9afaedbbd4', 'Cloudsoar', 'Flying', 'Soars above the clouds and loves heights! ☁️🦅', 'https://api.dicebear.com/7.x/bottts/svg?seed=cloudsoar&backgroundColor=skyblue', 'Uncommon', 56);

-- Total Pokemon: 20
